# Directly using the RawFile class

Using the RawFile class directly gives you access to the sls_detector_header and master file

In [1]:
#add the dev version of aare
import sys; sys.path.append('/home/l_msdetect/erik/aare/build')
from helpers import nb_aare_version
nb_aare_version()

from aare import RawMasterFile, File, RawFile, RawSubFile, DetectorType

#Our normal python imports
from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime as dt

base = Path('/mnt/sls_det_storage/matterhorn_data/aare_test_data/')

Example run on: **2025-01-15 08:18** with aare: **dev**

## Read all frames from a file

In [2]:
# For demo the subfiles contain 3,3,3,1 frames for a total of 10 frames
f = RawFile(base / 'ci/aare_test_data/jungfrau/jungfrau_single_master_0.json')
headers, data = f.read()
print(headers['frameNumber'])
print(f'{data.shape=}')

[ 1  2  3  4  5  6  7  8  9 10]
data.shape=(10, 512, 1024)


In [3]:
# Asking for more than the total number of frames, the actual number of frames are returned
f = RawFile(base / 'ci/aare_test_data/jungfrau/jungfrau_single_master_0.json')
headers, data = f.read_n(17)
print(f'{data.shape=}')

data.shape=(10, 512, 1024)


In [4]:
# When reading using read_n you get the number asked for, if not available the available frames
# and if at EOF a runtime error
f = RawFile(base / 'ci/aare_test_data/jungfrau/jungfrau_single_master_0.json')

for i in range(3):
    try:
        headers, data = f.read_n(7)
        print(f'{i}: {data.shape=}')
    except RuntimeError as e:
        print(f'{i}: {e}')

0: data.shape=(7, 512, 1024)
1: data.shape=(3, 512, 1024)
2: No frames left in file


## Looping over the file

In [5]:
with RawFile(base / 'ci/aare_test_data/jungfrau/jungfrau_single_master_0.json') as f:
    for header, data in f:
        print(header['frameNumber'], f'{data.shape=}')

[1] data.shape=(512, 1024)
[2] data.shape=(512, 1024)
[3] data.shape=(512, 1024)
[4] data.shape=(512, 1024)
[5] data.shape=(512, 1024)
[6] data.shape=(512, 1024)
[7] data.shape=(512, 1024)
[8] data.shape=(512, 1024)
[9] data.shape=(512, 1024)
[10] data.shape=(512, 1024)


**Looping with chunk_size**

In [6]:
with RawFile(base / 'ci/aare_test_data/jungfrau/jungfrau_single_master_0.json', chunk_size=3) as f:
    for header, data in f:
        print(header['frameNumber'], f'{data.shape=}')

[1 2 3] data.shape=(3, 512, 1024)
[4 5 6] data.shape=(3, 512, 1024)
[7 8 9] data.shape=(3, 512, 1024)
[10] data.shape=(1, 512, 1024)
